// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW63P6-ehnwtF-O1LQ_gzmRfNyCvn3Fzk',
    appId: '1:1088600291744:web:fff227332022e75c56ccc5',
    messagingSenderId: '1088600291744',
    projectId: 'lms-flutter-33171',
    authDomain: 'lms-flutter-33171.firebaseapp.com',
    storageBucket: 'lms-flutter-33171.firebasestorage.app',
    measurementId: 'G-78KQ7PHMX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLevIPSC9bLVN0DGqi57Pe1BbreRzLOO0',
    appId: '1:1088600291744:android:9bf0fd85562e926556ccc5',
    messagingSenderId: '1088600291744',
    projectId: 'lms-flutter-33171',
    storageBucket: 'lms-flutter-33171.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWYMGjXdpDhd3SklE1y9AmOr_D4CgUjzY',
    appId: '1:1088600291744:ios:3d8ffa06bcc07e1c56ccc5',
    messagingSenderId: '1088600291744',
    projectId: 'lms-flutter-33171',
    storageBucket: 'lms-flutter-33171.firebasestorage.app',
    iosBundleId: 'com.example.lmsMobileFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWYMGjXdpDhd3SklE1y9AmOr_D4CgUjzY',
    appId: '1:1088600291744:ios:3d8ffa06bcc07e1c56ccc5',
    messagingSenderId: '1088600291744',
    projectId: 'lms-flutter-33171',
    storageBucket: 'lms-flutter-33171.firebasestorage.app',
    iosBundleId: 'com.example.lmsMobileFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW63P6-ehnwtF-O1LQ_gzmRfNyCvn3Fzk',
    appId: '1:1088600291744:web:718c2a1e2109ce1856ccc5',
    messagingSenderId: '1088600291744',
    projectId: 'lms-flutter-33171',
    authDomain: 'lms-flutter-33171.firebaseapp.com',
    storageBucket: 'lms-flutter-33171.firebasestorage.app',
    measurementId: 'G-ZLSTLMNCF6',
  );

}